-- Investment Plans Table for storing user-generated investment plans
-- This table stores the complete investment plans generated by the Plan Creator

CREATE TABLE IF NOT EXISTS investment_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,

    -- User Input Data (from frontend form)
    financial_goals TEXT, -- User's financial goals input
    investment_preferences TEXT, -- User's investment preferences input

    -- Generated Plan Data (from agents)
    plan_data JSONB, -- Complete investment plan from agents

    -- Plan Metadata
    plan_name VARCHAR(255), -- User-defined or auto-generated plan name
    plan_type VARCHAR(50) DEFAULT 'GENERAL', -- RETIREMENT, HOUSE, EDUCATION, etc.
    risk_level VARCHAR(20), -- CONSERVATIVE, BALANCED, AGGRESSIVE
    time_horizon INTEGER, -- Investment time horizon in years
    target_amount DECIMAL(15,2), -- Target investment amount

    -- Agent Processing Data
    agent_2_data JSONB, -- Portfolio Agent output
    agent_3_data JSONB, -- Planner Agent output
    processing_status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, PROCESSING, COMPLETED, FAILED

    -- Plan Status
    is_active BOOLEAN DEFAULT true,
    is_favorite BOOLEAN DEFAULT false,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_reviewed_at TIMESTAMPTZ,

    -- Performance Tracking (for future use)
    expected_return DECIMAL(8,4), -- Expected annual return %
    actual_return DECIMAL(8,4), -- Actual return if implemented
    performance_notes TEXT
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_investment_plans_user_id ON investment_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_investment_plans_created_at ON investment_plans(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_investment_plans_plan_type ON investment_plans(plan_type);
CREATE INDEX IF NOT EXISTS idx_investment_plans_active ON investment_plans(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_investment_plans_status ON investment_plans(processing_status);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_investment_plans_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_investment_plans_updated_at
    BEFORE UPDATE ON investment_plans
    FOR EACH ROW EXECUTE FUNCTION update_investment_plans_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON investment_plans TO PUBLIC;

-- Sample investment plan insert (for testing)
/*
INSERT INTO investment_plans (
    user_id, financial_goals, investment_preferences, plan_data,
    plan_name, plan_type, risk_level, time_horizon, target_amount,
    processing_status, expected_return
) VALUES (
    (SELECT id_user FROM users LIMIT 1), -- Use first user for testing
    'Save for retirement in 30 years',
    'Moderate risk tolerance, prefer diversified ETFs',
    '{"monthly_contribution": 1000, "asset_allocation": {"stocks": 70, "bonds": 25, "alternatives": 5}}',
    'Retirement Plan 2055',
    'RETIREMENT',
    'BALANCED',
    30,
    500000.00,
    'COMPLETED',
    0.075
);
*/

COMMIT;